# sac_drone_fixed.yaml
torch_settings:
  device: cuda:0
  inference_device: cuda:0

behaviors:
  Drone:
    trainer_type: sac
    hyperparameters:
      batch_size: 1024
      buffer_size: 100000
      buffer_init_steps: 5000
      learning_rate: 3.0e-4
      learning_rate_schedule: constant
      tau: 0.005
      steps_per_update: 4.0
      reward_signal_steps_per_update: 4.0
      init_entcoef: 0.5
    network_settings:
      normalize: true
      vis_encode_type: resnet
      hidden_units: 512
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 5000000
    time_horizon: 1000
    summary_freq: 10000
    threaded: false   # <= flip to true later if stable

# environment_parameters:
#   goal_distance:
#     curriculum:
#       - name: Level1_CloseGoal
#         completion_criteria:
#           measure: reward
#           behavior: DroneSAC
#           signal_smoothing: true
#           min_lesson_length: 200
#           threshold: 0.6
#         value: 8.0
#       - name: Level2_FarGoal
#         completion_criteria:
#           measure: reward
#           behavior: DroneSAC
#           signal_smoothing: true
#           min_lesson_length: 300
#           threshold: 0.6
#         value: 20.0

#   obstacle_count:
#     curriculum:
#       - name: Level1_SparseObs
#         completion_criteria:
#           measure: reward
#           behavior: DroneSAC
#           signal_smoothing: true
#           min_lesson_length: 200
#           threshold: 0.6
#         value: 1
#       - name: Level2_DenseObs
#         completion_criteria:
#           measure: reward
#           behavior: DroneSAC
#           signal_smoothing: true
#           min_lesson_length: 300
#           threshold: 0.6
#         value: 5

#   progress_weight:
#     curriculum:
#       - name: Level1_ProgressHeavy
#         completion_criteria:
#           measure: reward
#           behavior: DroneSAC
#           signal_smoothing: true
#           min_lesson_length: 200
#           threshold: 0.6
#         value: 1.0
#       - name: Level2_ProgressLight
#         completion_criteria:
#           measure: reward
#           behavior: DroneSAC
#           signal_smoothing: true
#           min_lesson_length: 300
#           threshold: 0.6
#         value: 0.4

#   ray_length:
#     curriculum:
#       - name: Level1_ShortRays
#         completion_criteria:
#           measure: reward
#           behavior: DroneSAC
#           signal_smoothing: true
#           min_lesson_length: 200
#           threshold: 0.6
#         value: 12.0
#       - name: Level2_LongRays
#         completion_criteria:
#           measure: reward
#           behavior: DroneSAC
#           signal_smoothing: true
#           min_lesson_length: 300
#           threshold: 0.6
#         value: 20.0
